name: Auto Update Playlist (Unlimited & Secure)

on:
  
  workflow_dispatch: 

permissions:
  contents: write

jobs:
  update-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      
      - name: Checkout Public Repo
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install Dependencies
        run: pip install requests pytz
        
      
      - name: Checkout Private Repo (Sports)
        uses: actions/checkout@v3
        with:
          repository: srhady/Sports
          token: ${{ secrets.PAT_TOKEN }}
          path: private_repo
          
      
      - name: Run Python Script & Copy Outputs
        run: |
          cd private_repo
          python bot.py
          mv main_playlist.m3u ../
          mv main_playlist.json ../
          
      
      - name: Push Master Playlists to Private Repo
        run: |
          cd private_repo
          git config user.name "GitHub Action Bot"
          git config user.email "action@github.com"
          git add -A
          git commit -m "Auto update: Master files & cleanup" || echo "No changes to commit"
          git push
          
      
      - name: Clean up Private Files
        run: rm -rf private_repo
        
      
      - name: Commit and Push Main Playlists to Public Repo
        run: |
          git config user.name "GitHub Action Bot"
          git config user.email "action@github.com"
          git add main_playlist.m3u main_playlist.json
          git commit -m "Auto update: Main Playlists" || echo "No changes to commit"
          git push
